import numpy as np
import matplotlib.pyplot as plt

## Adversarial Data Generated by float Model
# Data
categories = [
    'float\n param float', '', 
    'quant\n param float', '', 
    'transaxx\n param float', '', 
    'float\n param quant', '', 
    'quant\n param quant', '', 
    'transaxx\n param quant', '', 
    'float\n param transaxx', '', 
    'quant\n param transaxx', '', 
    'transaxx\n param transaxx', ''
]
adv_acc = [0.0379, 0, 0.0384, 0, 0.0397, 0, 0.3724, 0, 0.3733, 0, 0.3661, 0, 0.1112, 0, 0.1121, 0, 0.4752, 0]
reg_acc = [0.8590, 0, 0.8588, 0, 0.8570, 0, 0.8558, 0, 0.8560, 0, 0.8526, 0, 0.1121, 0, 0.1125, 0, 0.5130, 0]
# Positions
bar_width = 0.4
gap = 0.2  # Space between pairs
positions = np.arange(len(categories) // 2) * (2 * bar_width + gap)

# Adjust positions for the two bars in each pair
positions_1 = positions
positions_2 = positions + bar_width

# Plot
plt.figure(1, figsize=(12, 6))
plt.bar(positions_1, adv_acc[::2], width=bar_width, label='Adversarial Data', color='orange')
plt.bar(positions_2, reg_acc[::2], width=bar_width, label='Standard Data', color='#3455eb')

# Formatting
plt.xticks(positions + bar_width / 2, categories[::2], rotation=45, ha='right')  # Use midpoints and labels for each pair
plt.xlabel('Execution Type')
plt.ylabel('Test Accuracy')
plt.title('Adversarial Accuracy of Different Models with FGSM (ε = 0.015) - Adversarial Data Generated by float Model')
plt.legend()
plt.tight_layout()
plt.show(block=False)




## Adversarial Data Generated by quant Model
# Data
categories = [
    'float\n param float', '', 
    'quant\n param float', '', 
    'transaxx\n param float', '', 
    'float\n param quant', '', 
    'quant\n param quant', '', 
    'transaxx\n param quant', '', 
    'float\n param transaxx', '', 
    'quant\n param transaxx', '', 
    'transaxx\n param transaxx', ''
]
adv_acc = [0.3666, 0, 0.3642, 0, 0.3663, 0, 0.0435, 0, 0.0425, 0, 0.0423, 0, 0.1105, 0, 0.1113, 0, 0.4750, 0]
reg_acc = [0.8590, 0, 0.8588, 0, 0.8570, 0, 0.8558, 0, 0.8560, 0, 0.8526, 0, 0.1121, 0, 0.1125, 0, 0.5130, 0]
# Positions
bar_width = 0.4
gap = 0.2  # Space between pairs
positions = np.arange(len(categories) // 2) * (2 * bar_width + gap)

# Adjust positions for the two bars in each pair
positions_1 = positions
positions_2 = positions + bar_width

# Plot
plt.figure(2, figsize=(12, 6))
plt.bar(positions_1, adv_acc[::2], width=bar_width, label='Adversarial Data', color='orange')
plt.bar(positions_2, reg_acc[::2], width=bar_width, label='Standard Data', color='#3455eb')

# Formatting
plt.xticks(positions + bar_width / 2, categories[::2], rotation=45, ha='right')  # Use midpoints and labels for each pair
plt.xlabel('Execution Type')
plt.ylabel('Test Accuracy')
plt.title('Adversarial Accuracy of Different Models with FGSM (ε = 0.015) - Adversarial Data Generated by quant Model')
plt.legend()
plt.tight_layout()
plt.show(block=False)




## Adversarial Data Generated by transaxx Model
# Data
categories = [
    'float\n param float', '', 
    'quant\n param float', '', 
    'transaxx\n param float', '', 
    'float\n param quant', '', 
    'quant\n param quant', '', 
    'transaxx\n param quant', '', 
    'float\n param transaxx', '', 
    'quant\n param transaxx', '', 
    'transaxx\n param transaxx', ''
]
adv_acc = [0.7760, 0, 0.7729, 0, 0.7692, 0, 0.7744, 0, 0.7778, 0, 0.7777, 0, 0.1119, 0, 0.1129, 0, 0.2497, 0]
reg_acc = [0.8590, 0, 0.8588, 0, 0.8570, 0, 0.8558, 0, 0.8560, 0, 0.8526, 0, 0.1121, 0, 0.1125, 0, 0.5130, 0]
# Positions
bar_width = 0.4
gap = 0.2  # Space between pairs
positions = np.arange(len(categories) // 2) * (2 * bar_width + gap)

# Adjust positions for the two bars in each pair
positions_1 = positions
positions_2 = positions + bar_width

# Plot
plt.figure(3, figsize=(12, 6))
plt.bar(positions_1, adv_acc[::2], width=bar_width, label='Adversarial Data', color='orange')
plt.bar(positions_2, reg_acc[::2], width=bar_width, label='Standard Data', color='#3455eb')

# Formatting
plt.xticks(positions + bar_width / 2, categories[::2], rotation=45, ha='right')  # Use midpoints and labels for each pair
plt.xlabel('Execution Type')
plt.ylabel('Test Accuracy')
plt.title('Adversarial Accuracy of Different Models with FGSM (ε = 0.015) - Adversarial Data Generated by transaxx Model')
plt.legend()
plt.tight_layout()
plt.show(block=True)
